# Generated by Django 4.2.23 on 2025-07-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='language',
            field=models.CharField(choices=[('pl', 'Polski'), ('en', 'English')], default='pl', max_length=2),
        ),
    ]
